fix(bashrc): remove deleted func

diff --git a/onion/bashrc b/onion/bashrc
--- a/onion/bashrc
+++ b/onion/bashrc
@@ -1,17 +1,30 @@
 #!/usr/bin/env bash
 iatest=$(expr index "$-" i)
-if [ -f /etc/bashrc ]; then . /etc/bashrc; fi
+if [ -f /etc/bashrc ]; then
+	. /etc/bashrc
+fi
 if [ -f /usr/share/bash-completion/bash_completion ]; then
 	. /usr/share/bash-completion/bash_completion
-elif [ -f /etc/bash_completion ]; then . /etc/bash_completion; fi
-readonly END="\033[0m" BLACK="\033[0;30m" BLACKB="\033[1;30m"
-readonly WHITE="\033[0;37m" WHITEB="\033[1;37m"
-readonly RED="\033[0;31m" REDB="\033[1;31m"
-readonly GREEN="\033[0;32m" GREENB="\033[1;32m"
-readonly YELLOW="\033[0;33m" YELLOWB="\033[1;33m"
-readonly BLUE="\033[0;34m" BLUEB="\033[1;34m"
-readonly PURPLE="\033[0;35m" PURPLEB="\033[1;35m"
-readonly LIGHTBLUE="\033[0;36m" LIGHTBLUEB="\033[1;36m"
+elif [ -f /etc/bash_completion ]; then
+	. /etc/bash_completion
+fi
+readonly END="\033[0m"
+readonly BLACK="\033[0;30m"
+readonly BLACKB="\033[1;30m"
+readonly WHITE="\033[0;37m"
+readonly WHITEB="\033[1;37m"
+readonly RED="\033[0;31m"
+readonly REDB="\033[1;31m"
+readonly GREEN="\033[0;32m"
+readonly GREENB="\033[1;32m"
+readonly YELLOW="\033[0;33m"
+readonly YELLOWB="\033[1;33m"
+readonly BLUE="\033[0;34m"
+readonly BLUEB="\033[1;34m"
+readonly PURPLE="\033[0;35m"
+readonly PURPLEB="\033[1;35m"
+readonly LIGHTBLUE="\033[0;36m"
+readonly LIGHTBLUEB="\033[1;36m"
 
 stats() {
 	history | awk '{print $2}' | awk 'BEGIN {FS="|"} {print $1}' | sort \
@@ -28,12 +41,13 @@ USAGE
 	$name [-h, --help]
 - get colored message
 	$name color message
-$(repeat_char - 80)
+$(printf '=%.0s' {1..80})
 by @mb6ockatf, Sat 01 Jul 2023 01:34:03 PM MSK
 end_of_message
 		return 0
 	fi
-	local color="$1" message="$2"
+	local color="$1"
+	local message="$2"
 	case "$color" in
 		black) color="${BLACK}" ;;
 		blackb) color="${BLACKB}" ;;
@@ -57,13 +71,13 @@ end_of_message
 }
 
 color::color_table() {
-	T='gYw'
+	local T='gYw'
 	echo -e "\n                 40m     41m     42m     43m\
 	44m     45m     46m     47m";
 	for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
 	    '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
 	    '  36m' '1;36m' '  37m' '1;37m'; do
-		FG=${FGs// /}
+		local FG=${FGs// /}
 		echo -en " $FGs \033[$FG  $T  "
 		for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
 			echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
@@ -101,48 +115,62 @@ ex() {
 			*.7z) 7z x "$1" ;;
 			*) echo "'$1' cannot be extracted via ex()" ;;
 		esac
-	else echo "'$1' is not a valid file"; return 22; fi
+	else
+		echo "'$1' is not a valid file"
+		return 22
+	fi
 }
 
 light() {
-	file="/sys/class/backlight/intel_backlight/brightness"
+	local file="/sys/class/backlight/intel_backlight/brightness"
 	if [[ ! -f $file ]]; then
-		echo "intel_backlight settings are not available"; return 2; fi
-	current=$(cat "$file"); new="$current"
-	if [ "$1" = "-dec" ]; then new=$(( current - $2 ))
-	elif [ "$1" = "-inc" ]; then new=$(( current + $2 ))
-	elif [ "$1" = "night" ]; then new=1; fi
+		echo "intel_backlight settings are not available"
+		return 2
+	fi
+	local current=$(cat "$file")
+	local new="$current"
+	if [ "$1" = "-dec" ]; then
+		new=$(( current - $2 ))
+	elif [ "$1" = "-inc" ]; then
+		new=$(( current + $2 ))
+	elif [ "$1" = "night" ]; then
+		new=1
+	fi
 	[[ "$new" -ge 0 ]] || exit
 	echo "$new" | sudo tee "$file"
 }
 
 commit() {
-	TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" \
+	local TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" \
 	"chore" "revert")
-	SCOPE=$(gum input --placeholder "scope")
+	local SCOPE=$(gum input --placeholder "scope")
 	test -n "$SCOPE" && SCOPE="($SCOPE)"
-	SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder \
+	local SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder \
 "Summary of this change")
-	DESCRIPTION=$(gum write --placeholder \
+	local DESCRIPTION=$(gum write --placeholder \
 "Details of this change (CTRL+D to finish)")
 	gum confirm "Commit changes?" && \
 	git commit -m "$SUMMARY" -m "$DESCRIPTION"
 }
 
 set_bash_prompt() {
-	LAST_RESULT=$?
-	DIVIDER="\[\e[30;1m\]"
-	COLOR_CMDCOUNT="\[\e[32;1m\]"  # green bold
-	COLOR_USERNAME="\[\e[37;0m\]"  # white
-	COLOR_USERHOSTAT="\[\e[36;1m\]"  # lightblueb
-	COLOR_HOSTNAME="\[\e[35;1m\]"  # purple bold
-	COLOR_GITBRANCH="\[\e[33;0m\]"  # yellow
-	COLOR_VENV="\[\e[33;1m\]"  # yellow bold
-	COLOR_PATH_OK="\[\e[32;1m\]"  # green bold
-	COLOR_PATH_ERR="\[\e[31;1m\]"  # red bold
-	COLOR_NONE="\[\e[0m\]"  # end
-	if [ $LAST_RESULT -eq 0 ]; then PATH_COLOR="$COLOR_PATH_OK"
-	else PATH_COLOR="$COLOR_PATH_ERR"; fi
+	local LAST_RESULT=$?
+	local DIVIDER="\[\e[30;1m\]"
+	local COLOR_CMDCOUNT="\[\e[32;1m\]"  # green bold
+	local COLOR_USERNAME="\[\e[37;0m\]"  # white
+	local COLOR_USERHOSTAT="\[\e[36;1m\]"  # lightblueb
+	local COLOR_HOSTNAME="\[\e[35;1m\]"  # purple bold
+	local COLOR_GITBRANCH="\[\e[33;0m\]"  # yellow
+	local COLOR_VENV="\[\e[33;1m\]"  # yellow bold
+	local COLOR_PATH_OK="\[\e[32;1m\]"  # green bold
+	local COLOR_PATH_ERR="\[\e[31;1m\]"  # red bold
+	local COLOR_NONE="\[\e[0m\]"  # end
+	local PATH_COLOR GIT_IS_AVAILABLE GIT_BRANCH git_answer
+	if [ $LAST_RESULT -eq 0 ]; then
+		PATH_COLOR="$COLOR_PATH_OK"
+	else
+		PATH_COLOR="$COLOR_PATH_ERR"
+	fi
 	PS1="\n${DIVIDER}"
 	PS1="${PS1}[${PATH_COLOR}\w${DIVIDER}"
 	PS1="${PS1}:${COLOR_CMDCOUNT}\#${DIVIDER}"
@@ -157,7 +185,7 @@ set_bash_prompt() {
 	if [ -n "$VIRTUAL_ENV" ]; then
 		PS1="${PS1}:${COLOR_VENV}$(basename "$VIRTUAL_ENV")${DIVIDER}"
 	fi
-	PS1="${PS1}]\n[${DIVIDER}${COLOR_USERNAME}\u${COLOR_USERHOSTAT}"
+	PS1="${PS1}][${DIVIDER}${COLOR_USERNAME}\u${COLOR_USERHOSTAT}"
 	PS1+="@${COLOR_HOSTNAME}\h${DIVIDER}]${COLOR_NONE} "
 }
 
@@ -167,8 +195,10 @@ mcd() {
 }
 
 wttr() {
-	local city="$1" options="$2" header="Accept-Language: en"
-	if [[ "$options" -eq "" ]]; then options="1FnQp"; fi
+	local city="$1"
+	local options="$2"
+	local header="Accept-Language: en"
+	[[ "$options" -eq "" ]] && options="1FnQp"
 	curl -H "$header " "wttr.in/$city?$options"
 }
 
@@ -188,18 +218,50 @@ ftext() {
 	grep -iIHrn --color=always "$1" . | less -r
 }
 
-mvg() { if [ -d "$2" ]; then mv "$1" "$2" && cd "$2"; else mv "$1" "$3"; fi }
-viewlines () { sed -n ''$1','$2'p' $3; }
-bashrc() { reload=true; . ~/.bashrc > /dev/null 2>&1; reload=false; }
-cpg() { if [ -d "$2" ]; then cp "$1" "$2" && cd "$2"; else cp "$1" "$2"; fi; }
-repc() { for ((i = 1; i < $2; i++)); do echo -n "$1"; done; }
-pwdtail() { pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'; }
+mvg() {
+	if [ -d "$2" ]; then
+		mv "$1" "$2" && cd "$2"
+	else
+		mv "$1" "$3"
+	fi
+}
+
+viewlines () {
+	sed -n "$1,$2p" "$3"
+}
+
+bashrc() {
+	reload=true
+	. ~/.bashrc > /dev/null 2>&1
+	reload=false
+}
+
+cpg() {
+	if [ -d "$2" ]; then
+		cp "$1" "$2" && cd "$2"
+	else
+		cp "$1" "$2"
+	fi
+}
+
+repc() {
+	for ((i = 1; i < $2; i++)); do
+		echo -n "$1"
+	done
+}
+
+pwdtail() {
+	pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'
+}
 
 up() {
-	local d="" limit=$1
-	for ((i=1 ; i <= limit ; i++)); do d=$d/..;  done
+	local d=""
+	local limit=$1
+	for ((i=1 ; i <= limit ; i++)); do
+		d=$d/..
+	done
 	d=$(echo $d | sed 's/^\///')
-	if [ -z "$d" ]; then d=..; fi
+	[[ -z "$d" ]] && d=..
 	cd "$d"
 }
 
@@ -208,8 +270,10 @@ distribution() {
 	if [[ -r /etc/rc.d/init.d/functions ]]; then
 		. /etc/rc.d/init.d/functions
 		[[ zz`type -t passed 2>/dev/null` == "zzfunction" ]] && dtype="redhat"
-	elif [[ -f /etc/arch-release ]]; then dtype="arch"
-	elif [[ -r /etc/rc.status ]]; then . /etc/rc.status
+	elif [[ -f /etc/arch-release ]]; then
+		dtype="arch"
+	elif [[ -r /etc/rc.status ]]; then
+		. /etc/rc.status
 		[[ zz`type -t rc_reset 2>/dev/null` == "zzfunction" ]] && dtype="suse"
 	elif [[ -r /lib/lsb/init-functions ]]; then
 		. /lib/lsb/init-functions
@@ -218,8 +282,11 @@ distribution() {
 	elif [[ -r /etc/init.d/functions.sh ]]; then
 		. /etc/init.d/functions.sh
 		[[ zz`type -t ebegin 2>/dev/null` == "zzfunction" ]] && dtype="gentoo"
-	elif [[ -s /etc/mandriva-release ]]; then dtype="mandriva"
-	elif [[ -s /etc/slackware-version ]]; then dtype="slackware"; fi
+	elif [[ -s /etc/mandriva-release ]]; then
+		dtype="mandriva"
+	elif [[ -s /etc/slackware-version ]]; then
+		dtype="slackware"
+	fi
 	echo "$dtype"
 }
 
@@ -228,15 +295,26 @@ ver() {
 	if [[ "$dtype" == "redhat" ]]; then
 		if [[ -s /etc/redhat-release ]]; then
 			cat /etc/redhat-release && uname -a
-		else cat /etc/issue && uname -a; fi
-	elif [[ "$dtype" == "suse" ]]; then cat /etc/SuSE-release
-	elif [[ "$dtype" == "debian" ]]; then lsb_release -a
-	elif [[ "$dtype" == "gentoo" ]]; then cat /etc/gentoo-release
-	elif [[ "$dtype" == "mandriva" ]]; then cat /etc/mandriva-release
-	elif [[ "$dtype" == "slackware" ]]; then cat /etc/slackware-version
+		else
+			cat /etc/issue && uname -a
+		fi
+	elif [[ "$dtype" == "suse" ]]; then
+		cat /etc/SuSE-release
+	elif [[ "$dtype" == "debian" ]]; then
+		lsb_release -a
+	elif [[ "$dtype" == "gentoo" ]]; then
+		cat /etc/gentoo-release
+	elif [[ "$dtype" == "mandriva" ]]; then
+		cat /etc/mandriva-release
+	elif [[ "$dtype" == "slackware" ]]; then
+		cat /etc/slackware-version
 	else
-		if [[ -s /etc/issue ]]; then cat /etc/issue
-		else echo "Error: Unknown distribution"; exit 1; fi
+		if [[ -s /etc/issue ]]; then
+			cat /etc/issue
+		else
+			echo "Error: Unknown distribution"
+			exit 1
+		fi
 	fi
 }
 
@@ -263,9 +341,12 @@ apacheconfig() {
 }
 
 phpconfig() {
-	if [[ -f /etc/php.ini ]]; then sedit /etc/php.ini
-	elif [[ -f /etc/php/php.ini ]]; then sedit /etc/php/php.ini
-	elif [[ -f /etc/php5/php.ini ]]; then sedit /etc/php5/php.ini
+	if [[ -f /etc/php.ini ]]; then
+		sedit /etc/php.ini
+	elif [[ -f /etc/php/php.ini ]]; then
+		sedit /etc/php/php.ini
+	elif [[ -f /etc/php5/php.ini ]]; then
+		sedit /etc/php5/php.ini
 	elif [[ -f /usr/bin/php5/bin/php.ini ]]; then
 		sedit /usr/bin/php5/bin/php.ini
 	elif [[ -f /etc/php5/apache2/php.ini ]]; then
@@ -278,12 +359,18 @@ phpconfig() {
 }
 
 mysqlconfig() {
-	if [[ -f /etc/my.cnf ]]; then sedit /etc/my.cnf
-	elif [[ -f /etc/mysql/my.cnf ]]; then sedit /etc/mysql/my.cnf
-	elif [[ -f /usr/local/etc/my.cnf ]]; then sedit /usr/local/etc/my.cnf
-	elif [[ -f /usr/bin/mysql/my.cnf ]]; then sedit /usr/bin/mysql/my.cnf
-	elif [[ -f ~/my.cnf ]]; then sedit ~/my.cnf
-	elif [[ -f ~/.my.cnf ]]; then sedit ~/.my.cnf
+	if [[ -f /etc/my.cnf ]]; then
+		sedit /etc/my.cnf
+	elif [[ -f /etc/mysql/my.cnf ]]; then
+		sedit /etc/mysql/my.cnf
+	elif [[ -f /usr/local/etc/my.cnf ]]; then
+		sedit /usr/local/etc/my.cnf
+	elif [[ -f /usr/bin/mysql/my.cnf ]]; then
+		sedit /usr/bin/mysql/my.cnf
+	elif [[ -f ~/my.cnf ]]; then
+		sedit ~/my.cnf
+	elif [[ -f ~/.my.cnf ]]; then
+		sedit ~/.my.cnf
 	else
 		echo "Error: my.cnf file could not be found."
 		echo "Searching for possible locations:"
@@ -317,7 +404,7 @@ ifconfig_help() {
 }
 
 ls_help() {
-cat << E
+cat << End
 ls -Al  # show hidden files
 ls -lX --ignore-backups  # sort by extension (ls -lXB)
 ls -lSr  # sort by size
@@ -331,12 +418,12 @@ ls -ls  # long listing format
 ls -lp  # alphabetical sort
 ls -l | egrep -v '^d'"  # files only (remove backslashes)
 ls -l | egrep '^d'"  # directories only (remove backslashes)
-E
+End
 }
 
 ping_help() {
-cat << E ping='ping -c 5' fastping='ping -c 100 -i 0.2' ping8="ping 8.8.8.8"
-E
+cat << End ping='ping -c 5' fastping='ping -c 100 -i 0.2' ping8="ping 8.8.8.8"
+End
 }
 
 chmod_help() {
@@ -359,61 +446,120 @@ moo() {
 # alias psmem10='ps auxf | sort -nr -k 4 | head -10'
 # alias pscpu='ps auxf | sort -nr -k 3'
 # alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
-readonly -f light viewlines ex stats repc commit set_bash_prompt mcd wttr
-readonly -f clock ftext cpg mvg up pwdtail distribution ver apachelog
-readonly -f apacheconfig phpconfig mysqlconfig trim folderssort ifconfig_help
-readonly -f color::colorful color::color_table color::form_output rot13 bashrc
-readonly -f ls_help ping_help chmod_help
-alias less="less --use-color" more=less ls='ls -Fh --color=auto'
-alias grep='grep --colour=auto' egrep='grep -E' fgrep='grep -F'
-alias cal="cal | pv -qL 10" todo="todo.sh -@ -+ -c -t -v"
+readonly -f light
+readonly -f viewlines
+readonly -f ex
+readonly -f stats
+readonly -f repc
+readonly -f commit
+readonly -f set_bash_prompt
+readonly -f mcd
+readonly -f wttr
+readonly -f clock
+readonly -f ftext
+readonly -f cpg
+readonly -f mvg
+readonly -f up
+readonly -f pwdtail
+readonly -f distribution
+readonly -f ver
+readonly -f apachelog
+readonly -f apacheconfig
+readonly -f phpconfig
+readonly -f mysqlconfig
+readonly -f trim
+readonly -f folderssort
+readonly -f ifconfig_help
+readonly -f color::colorful
+readonly -f color::color_table
+readonly -f color::form_output
+readonly -f rot13
+readonly -f bashrc
+readonly -f ls_help
+readonly -f ping_help
+readonly -f chmod_help
+alias less="less --use-color"
+alias more=less
+alias ls='ls -Fh --color=auto'
+alias grep='grep --colour=auto'
+alias egrep='grep -E'
+alias fgrep='grep -F'
+alias cal="cal | pv -qL 10"
+alias todo="todo.sh -@ -+ -c -t -v"
 alias shellcheck='shellcheck -C'
-alias cowsay='cowsay -d -W 80' moo='fortune | cowsay | pv -qL 30'
-alias df='df -h' free='free -h' ln='ln -i' cp='cp -i'
+alias cowsay='cowsay -d -W 80'
+alias moo='fortune | cowsay | pv -qL 30'
+alias df='df -h'
+alias free='free -h'
+alias ln='ln -i'
+alias cp='cp -i'
 # alias np='nano -w PKGBUILD'
-alias chown='chown --preserve-root' chmod='chmod --preserve-root'
-alias chgrp='chgrp --preserve-root' rm='rm -ivI --preserve-root'
-alias ifconfig=ifconfig_help netstat='ss -v' iwconfig='iw --version'
-alias scp="echo 'use $(color::form_output red rsync)'" dig='drill -v'
-alias arp='echo "arp -> ip n"' nslookup='echo "nslookup -> drill or host"'
-alias iptunnel='echo "iptunnel -> ip t"' ipmaddr='echo "ipmaddr -> ip maddr"'
-alias nameif='echo "nameif -> ip l"' route='echo "route -> ip r"'
-alias poweroff='systemctl poweroff' halt='systemctl halt'
-alias reboot='systemctl reboot' clear='sl -adF; clear'
+alias chown='chown --preserve-root'
+alias chmod='chmod --preserve-root'
+alias chgrp='chgrp --preserve-root'
+alias rm='rm -ivI --preserve-root'
+alias ifconfig=ifconfig_help
+alias netstat='ss -v'
+alias iwconfig='iw --version'
+alias scp="echo 'use $(color::form_output red rsync)'"
+alias dig='drill -v'
+alias arp='echo "arp -> ip n"'
+alias nslookup='echo "nslookup -> drill or host"'
+alias iptunnel='echo "iptunnel -> ip t"'
+alias ipmaddr='echo "ipmaddr -> ip maddr"'
+alias nameif='echo "nameif -> ip l"'
+alias route='echo "route -> ip r"'
+alias poweroff='systemctl poweroff'
+alias halt='systemctl halt'
+alias reboot='systemctl reboot'
+alias clear='sl -adF; clear'
 alias google-chrome='/usr/bin/google-chrome-stable %U'
-alias sha1='openssl sha1' echoi='rev' mkdir='mkdir -pv' meminfo='free -l'
-alias mount='mount | column -t' diskspace="du -S | sort -n -r |more"
-alias folders='du -h --max-depth=1' tree='tree -CAhF --dirsfirst'
+alias mkdir='mkdir -pv'
+alias meminfo='free -l'
+alias mount='mount | column -t'
+alias diskspace="du -S | sort -n -r |more"
+alias folders='du -h --max-depth=1'
+alias tree='tree -CAhF --dirsfirst'
 alias treed='tree -CAFd'
 alias mountedinfo='df -hT'
 alias cpuinfo='lscpu'
 alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
 alias wget='wget -c'
-alias clip='xclip -sel clip'
-alias pwrd='cat /etc/passwd | column -t -s ":"'
 alias bc='bc -l'
+
+alias pwrd='cat /etc/passwd | column -t -s ":"'
+alias clip='xclip -sel clip'
 alias h='cat .bash_history | sort | uniq -c | sort -nr'
 alias j='jobs -l'
 alias f="find . | grep "
 [ -d "$HOME/.atom" ] && alias atom="~/.atom/atom &"
 shopt -s checkwinsize expand_aliases histappend
-export CLICOLOR=1 QT_SELECT=4 PYENV_ROOT="$HOME/.pyenv" HISTFILESIZE=2000
+export CLICOLOR=1
+export QT_SELECT=4
+export PYENV_ROOT="$HOME/.pyenv"
+export HISTFILESIZE=2000
 export HISTCONTROL=ignoreboth:erasedups
-export PROMPT_COMMAND=set_bash_prompt BROWSER=/usr/bin/chromium EDITOR=vim
+export PROMPT_COMMAND=set_bash_prompt
+export BROWSER=/usr/bin/chromium
+export EDITOR=vim
 export LESS_TERMCAP_mb=$(tput bold; tput setaf 2)  # green
 export LESS_TERMCAP_md=$(tput bold; tput setaf 6)  # cyan
-export LESS_TERMCAP_me=$(tput sgr0) LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
+export LESS_TERMCAP_me=$(tput sgr0)
+export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
 export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)  # yellowonblue
 export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
 export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7)  # white
-export LESS_TERMCAP_mr=$(tput rev) LESS_TERMCAP_mh=$(tput dim)
-export LESS_TERMCAP_ZN=$(tput ssubm) LESS_TERMCAP_ZV=$(tput rsubm)
-export LESS_TERMCAP_ZO=$(tput ssupm) LESS_TERMCAP_ZW=$(tput rsupm)
+export LESS_TERMCAP_mr=$(tput rev)
+export LESS_TERMCAP_mh=$(tput dim)
+export LESS_TERMCAP_ZN=$(tput ssubm)
+export LESS_TERMCAP_ZV=$(tput rsubm)
+export LESS_TERMCAP_ZO=$(tput ssupm)
+export LESS_TERMCAP_ZW=$(tput rsupm)
 export GROFF_NO_SGR=1  # For Konsole and Gnome-terminal
 command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
 eval "$(pyenv init -)"
 bind -f  ~/.inputrc
-if [[ "$(whoami)" != "root" && "$reload" != "true" ]]; then moo; fi
+[[ "$(whoami)" != "root" && "$reload" != "true" ]] && moo
 # rate.sx
 # parrotsay
 # rickroll: https://github.com/keroserene/rickrollrc
