chore(bashrc): pass shellcheck test

diff --git a/onion/bashrc b/onion/bashrc
--- a/onion/bashrc
+++ b/onion/bashrc
@@ -1,17 +1,19 @@
 #!/usr/bin/env bash
 shopt -s checkwinsize expand_aliases histappend checkhash
 set -o posix
-iatest=$(expr index "$-" i)
+# shellcheck disable=SC1091
 [[ -f /etc/bashrc ]] && . /etc/bashrc
+# shellcheck disable=SC1091
 [[ -f /etc/bash_completion ]] && . /etc/bash_completion
+# shellcheck disable=SC1091
 [[ -f /usr/share/bash-completion/bash_completion ]] && \
 	. /usr/share/bash-completion/bash_completion
 readonly END="\033[0m" BLACK="\033[0;30m" BLACKB="\033[1;30m" \
-	WHITE="\033[0;37m" WHITEB="\033[1;37m" RED="\033[0;31m" REDB="\033[1;31m" \
-	GREEN="\033[0;32m" GREENB="\033[1;32m" YELLOW="\033[0;33m" \
-	YELLOWB="\033[1;33m" BLUE="\033[0;34m" BLUEB="\033[1;34m" \
-	PURPLE="\033[0;35m" PURPLEB="\033[1;35m" LIGHTBLUE="\033[0;36m" \
-	LIGHTBLUEB="\033[1;36m"
+	WHITE="\033[0;37m" WHITEB="\033[1;37m" RED="\033[0;31m" \
+	REDB="\033[1;31m" GREEN="\033[0;32m" GREENB="\033[1;32m" \
+	YELLOW="\033[0;33m" YELLOWB="\033[1;33m" BLUE="\033[0;34m" \
+	BLUEB="\033[1;34m" PURPLE="\033[0;35m" PURPLEB="\033[1;35m" \
+	LIGHTBLUE="\033[0;36m" LIGHTBLUEB="\033[1;36m"
 
 stats() {
 	history | awk '{print $2}' | awk 'BEGIN {FS="|"} {print $1}' | sort \
@@ -108,9 +110,11 @@ ex() {
 
 light() {
 	local file="/sys/class/backlight/intel_backlight/brightness"
-	[[ ! -f $file ]] && echo "intel_backlight settings are not available" && \
-		return 2
-	local current=$(cat "$file") new="$current"
+	[[ ! -f $file ]] && echo "intel_backlight settings are not available" \
+		&& return 2
+	declare current
+	current="$(cat "$file")"
+	local new="$current"
 	if [[ "$1" = "-dec" ]]; then
 		new=$(( current - $2 ))
 	elif [[ "$1" = "-inc" ]]; then
@@ -123,10 +127,11 @@ light() {
 }
 
 commit() {
-	local TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" \
+	declare TYPE SUMMARY
+	TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" \
 	"chore" "revert") SCOPE=$(gum input --placeholder "scope")
 	test -n "$SCOPE" && SCOPE="($SCOPE)"
-	local SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder \
+	SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder \
 "Summary of this change") DESCRIPTION=$(gum write --placeholder \
 "Details of this change (CTRL+D to finish)")
 	gum confirm "Commit changes?" && \
@@ -188,7 +193,7 @@ ftext() {
 
 mvg() {
 	if [ -d "$2" ]; then
-		mv "$1" "$2" && cd "$2"
+		mv "$1" "$2" && cd "$2" || return
 	else
 		mv "$1" "$3"
 	fi
@@ -200,13 +205,14 @@ viewlines () {
 
 bashrc() {
 	reload=true
+	# shellcheck disable=SC1090
 	. ~/.bashrc > /dev/null 2>&1
 	reload=false
 }
 
 cpg() {
 	if [ -d "$2" ]; then
-		cp "$1" "$2" && cd "$2"
+		cp "$1" "$2" && cd "$2" || return
 	else
 		cp "$1" "$2"
 	fi
@@ -223,26 +229,33 @@ up() {
 	done
 	d=$(echo $d | sed 's/^\///')
 	[[ -z "$d" ]] && d=..
-	cd "$d"
+	cd "$d" || return
 }
 
 distribution() {
 	local dtype="unknown"
 	if [[ -r /etc/rc.d/init.d/functions ]]; then
+		# shellcheck disable=SC1091
 		. /etc/rc.d/init.d/functions
-		[[ zz`type -t passed 2>/dev/null` == "zzfunction" ]] && dtype="redhat"
+		[[ zz"$(type -t passed 2>/dev/null)" == "zzfunction" ]] && \
+			dtype="redhat"
 	elif [[ -f /etc/arch-release ]]; then
 		dtype="arch"
 	elif [[ -r /etc/rc.status ]]; then
+		# shellcheck disable=SC1091
 		. /etc/rc.status
-		[[ zz`type -t rc_reset 2>/dev/null` == "zzfunction" ]] && dtype="suse"
+		[[ zz"$(type -t rc_reset 2>/dev/null)" == "zzfunction" ]] && \
+			dtype="suse"
 	elif [[ -r /lib/lsb/init-functions ]]; then
+		# shellcheck disable=SC1091
 		. /lib/lsb/init-functions
-		[[ zz`type -t log_begin_msg 2>/dev/null` == "zzfunction" ]] && \
+		[[ zz"$(type -t log_begin_msg 2>/dev/null)" == "zzfunction" ]] && \
 			dtype="debian"
 	elif [[ -r /etc/init.d/functions.sh ]]; then
+		# shellcheck disable=SC1091
 		. /etc/init.d/functions.sh
-		[[ zz`type -t ebegin 2>/dev/null` == "zzfunction" ]] && dtype="gentoo"
+		[[ zz"$(type -t ebegin 2>/dev/null)" == "zzfunction" ]] && \
+			dtype="gentoo"
 	elif [[ -s /etc/mandriva-release ]]; then
 		dtype="mandriva"
 	elif [[ -s /etc/slackware-version ]]; then
@@ -252,102 +265,76 @@ distribution() {
 }
 
 ver() {
-	local dtype="$(distribution)"
+	declare dtype
+	dtype="$(distribution)"
 	if [[ "$dtype" == "redhat" ]]; then
-		if [[ -s /etc/redhat-release ]]; then
-			cat /etc/redhat-release && uname -a
-		else
-			cat /etc/issue && uname -a
-		fi
-	elif [[ "$dtype" == "suse" ]]; then
-		cat /etc/SuSE-release
-	elif [[ "$dtype" == "debian" ]]; then
-		lsb_release -a
-	elif [[ "$dtype" == "gentoo" ]]; then
-		cat /etc/gentoo-release
-	elif [[ "$dtype" == "mandriva" ]]; then
-		cat /etc/mandriva-release
-	elif [[ "$dtype" == "slackware" ]]; then
-		cat /etc/slackware-version
-	else
-		if [[ -s /etc/issue ]]; then
-			cat /etc/issue
-		else
-			echo "Error: Unknown distribution" && exit 1
-		fi
+		[[ -s /etc/redhat-release ]] && cat /etc/redhat-release && \
+			uname -a && return
+		cat /etc/issue && uname -a && return
 	fi
+	[[ "$dtype" == "suse" ]] && cat /etc/SuSE-release && return
+	[[ "$dtype" == "debian" ]] && lsb_release -a && return
+	[[ "$dtype" == "gentoo" ]] && cat /etc/gentoo-release && return
+	[[ "$dtype" == "mandriva" ]] && cat /etc/mandriva-release && return
+	[[ "$dtype" == "slackware" ]] && cat /etc/slackware-version && return
+	[[ -s /etc/issue ]] && cat /etc/issue && return
+	echo "Error: Unknown distribution" && exit 1
 }
 
 apachelog() {
-	if [[ -f /etc/httpd/conf/httpd.conf ]]; then
+	[[ -f /etc/httpd/conf/httpd.conf ]] && \
 		cd /var/log/httpd && \
-			ls -xAh && multitail --no-repeat -c -s 2 /var/log/httpd/*_log
-	else
-		cd /var/log/apache2 && \
-			ls -xAh && multitail --no-repeat -c -s 2 /var/log/apache2/*.log
-	fi
+		ls -xAh && multitail --no-repeat -c -s 2 \
+			/var/log/httpd/*_log && return
+	cd /var/log/apache2 && ls -xAh && multitail --no-repeat -c -s 2 \
+			/var/log/apache2/*.log && return
 }
 
 apacheconfig() {
-	if [[ -f /etc/httpd/conf/httpd.conf ]]; then
-		sedit /etc/httpd/conf/httpd.conf
-	elif [[ -f /etc/apache2/apache2.conf ]]; then
-		sedit /etc/apache2/apache2.conf
-	else
-		echo "Error: Apache config file could not be found. \
-			Searching for possible locations:"
-		sudo updatedb && locate httpd.conf && locate apache2.conf
-	fi
+	[[ -f /etc/httpd/conf/httpd.conf ]] && \
+		sedit /etc/httpd/conf/httpd.conf && return
+	[[ -f /etc/apache2/apache2.conf ]] && \
+		sedit /etc/apache2/apache2.conf && return
+	echo "Error: Apache config file could not be found. \
+		Searching for possible locations:"
+	sudo updatedb && locate httpd.conf && locate apache2.conf
 }
 
 phpconfig() {
-	if [[ -f /etc/php.ini ]]; then
-		sedit /etc/php.ini
-	elif [[ -f /etc/php/php.ini ]]; then
-		sedit /etc/php/php.ini
-	elif [[ -f /etc/php5/php.ini ]]; then
-		sedit /etc/php5/php.ini
-	elif [[ -f /usr/bin/php5/bin/php.ini ]]; then
-		sedit /usr/bin/php5/bin/php.ini
-	elif [[ -f /etc/php5/apache2/php.ini ]]; then
-		sedit /etc/php5/apache2/php.ini
-	else
-		echo "Error: php.ini file could not be found.\
-			Searching for possible locations:"
-		sudo updatedb && locate php.ini
-	fi
+	[[ -f /etc/php.ini ]] && sedit /etc/php.ini && return
+	[[ -f /etc/php/php.ini ]] && sedit /etc/php/php.ini && return
+	[[ -f /etc/php5/php.ini ]] && sedit /etc/php5/php.ini && return
+	[[ -f /usr/bin/php5/bin/php.ini ]] && \
+		sedit /usr/bin/php5/bin/php.ini && return
+	[[ -f /etc/php5/apache2/php.ini ]] && \
+		sedit /etc/php5/apache2/php.ini && return
+	echo "Error: php.ini file could not be found.\
+		Searching for possible locations:"
+	sudo updatedb && locate php.ini
 }
 
 mysqlconfig() {
-	if [[ -f /etc/my.cnf ]]; then
-		sedit /etc/my.cnf
-	elif [[ -f /etc/mysql/my.cnf ]]; then
-		sedit /etc/mysql/my.cnf
-	elif [[ -f /usr/local/etc/my.cnf ]]; then
-		sedit /usr/local/etc/my.cnf
-	elif [[ -f /usr/bin/mysql/my.cnf ]]; then
-		sedit /usr/bin/mysql/my.cnf
-	elif [[ -f ~/my.cnf ]]; then
-		sedit ~/my.cnf
-	elif [[ -f ~/.my.cnf ]]; then
-		sedit ~/.my.cnf
-	else
-		echo "Error: my.cnf file could not be found.\
-			Searching for possible locations:"
-		sudo updatedb && locate my.cnf
-	fi
+	[[ -f /etc/my.cnf ]] && sedit /etc/my.cnf && return
+	[[ -f /etc/mysql/my.cnf ]] && sedit /etc/mysql/my.cnf && return
+	[[ -f /usr/local/etc/my.cnf ]] && sedit /usr/local/etc/my.cnf && return
+	[[ -f /usr/bin/mysql/my.cnf ]] && sedit /usr/bin/mysql/my.cnf && return
+	[[ -f ~/my.cnf ]] && sedit ~/my.cnf && return
+	[[ -f ~/.my.cnf ]] && sedit ~/.my.cnf && return
+	echo "Error: my.cnf file could not be found.\
+		Searching for possible locations:"
+	sudo updatedb && locate my.cnf
 }
 
 rot13() {
 	if [[ $# -eq 0 ]]; then
-		tr '[a-m][n-z][A-M][N-Z]' '[n-z][a-m][N-Z][A-M]'
+		tr 'a-mn-zA-MN-Z' 'n-za-mN-ZA-M'
 	else
-		echo $* | tr '[a-m][n-z][A-M][N-Z]' '[n-z][a-m][N-Z][A-M]'
+		echo "$@" | tr 'a-mn-zA-MN-Z' 'n-za-mN-ZA-M'
 	fi
 }
 
 trim() {
-	local var=$@
+	local var="$*"
 	var="${var#"${var%%[![:space:]]*}"}"  # remove leading whitespace chars
 	var="${var%"${var##*[![:space:]]}"}"  # remove trailing whitespace chars
 	echo -n "$var"
@@ -358,7 +345,8 @@ folderssort() {
 }
 
 ifconfig() {
-	local colored="$(color_form_output red 'ip a')"
+	declare colored
+	colored="$(color_form_output red 'ip a')"
 	echo "ifconfig is deprecated with net-tools pkg. use $colored"
 }
 
@@ -406,19 +394,21 @@ readonly -f light viewlines ex stats commit set_bash_prompt mcd wttr clock \
 	phpconfig mysqlconfig trim folderssort ifconfig color_colorful \
 	color_color_table color_form_output rot13 bashrc ls_help ping_help \
 	chmod_help
-alias less="less --use-color" ls='ls -Fh --color=auto' more=less \
-	cpuinfo='lscpu' grep='grep --colour=auto' egrep='grep -E' fgrep='grep -F' \
-	cal="cal | pv -qL 10" ln='ln -i' cp='cp -i' df='df -h' \
+alias less="less --use-color" ls='ls -Fh --color=auto' cpuinfo='lscpu' \
+	grep='grep --colour=auto' egrep='grep -E' fgrep='grep -F' \
+	cal="cal -m | pv -qL 10" ln='ln -i' cp='cp -i' df='df -h' \
 	chown='chown --preserve-root' chmod='chmod --preserve-root' \
 	chgrp='chgrp --preserve-root' rm='rm -ivI --preserve-root' \
-	scp="echo 'use $(color_form_output red rsync)'" \
-	netstat='ss -v' iwconfig='iw --version' dig='drill -v' \
-	arp='echo "arp -> ip n"' nslookup='echo "nslookup -> drill or host"' \
-	iptunnel='echo "iptunnel -> ip t"' ipmaddr='echo "ipmaddr -> ip maddr"' \
-	nameif='echo "nameif -> ip l"' route='echo "route -> ip r"' \
-	mkdir='mkdir -pv' mount='mount | column -t' wget='wget -c' bc='bc -l'
+	scp='echo "use $(color_form_output red rsync)"' netstat='ss -v' \
+	iwconfig='iw --version' dig='drill -v' arp='echo "arp -> ip n"' \
+	nslookup='echo "nslookup -> drill or host"' \
+	iptunnel='echo "iptunnel -> ip t"' \
+	ipmaddr='echo "ipmaddr -> ip maddr"' nameif='echo "nameif -> ip l"' \
+	route='echo "route -> ip r"' mkdir='mkdir -pv' \
+	mount='mount | column -t' wget='wget -c'
 # alias np='nano -w PKGBUILD'
-
+command -v bc &> /dev/null && alias bc='bc -l'
+command -v less &> /dev/null && alias more='less'
 command -v wget &> /dev/null && alias wget='wget -c'
 command -v bc &> /dev/null && alias bc='bc -l'
 command -v todo.sh &> /dev/null && alias todo='todo.sh -@ -+ -c -t -v'
@@ -445,18 +435,26 @@ command -v tree &> /dev/null && alias tree='tree -CAhF --dirsfirst' \
 	h='cat .bash_history | sort | uniq -c | sort -nr'
 [[ -f /etc/passwd ]] && alias pwrd='cat /etc/passwd | column -t -s ":"'
 [[ -d "$HOME/.atom" ]] && alias atom='~/.atom/atom &'
+declare -x LESS_TERMCAP_mb LESS_TERMCAP_md LESS_TERMCAP_me LESS_TERMCAP_ue \
+	LESS_TERMCAP_so LESS_TERMCAP_se LESS_TERMCAP_us LESS_TERMCAP_mr \
+	LESS_TERMCAP_mh LESS_TERMCAP_ZN LESS_TERMCAP_ZV LESS_TERMCAP_ZO \
+	LESS_TERMCAP_ZW
+LESS_TERMCAP_mb=$(tput bold; tput setaf 2)
+LESS_TERMCAP_md=$(tput bold; tput setaf 6)
+LESS_TERMCAP_me=$(tput sgr0)
+LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
+LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)
+LESS_TERMCAP_se=$(tput rmso; tput sgr0)
+LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7)
+LESS_TERMCAP_mr=$(tput rev)
+LESS_TERMCAP_mh=$(tput dim)
+LESS_TERMCAP_ZN=$(tput ssubm)
+LESS_TERMCAP_ZV=$(tput rsubm)
+LESS_TERMCAP_ZO=$(tput ssupm)
+LESS_TERMCAP_ZW=$(tput rsupm)
 export POSIXLY_CORRECT=true CLICOLOR=1 QT_SELECT=4 PYENV_ROOT="$HOME/.pyenv" \
 	HISTFILESIZE=2000 HISTCONTROL=ignoreboth:erasedups \
 	PROMPT_COMMAND=set_bash_prompt BROWSER=/usr/bin/chromium EDITOR=vim \
-	LESS_TERMCAP_mb=$(tput bold; tput setaf 2) \
-	LESS_TERMCAP_md=$(tput bold; tput setaf 6) \
-	LESS_TERMCAP_me=$(tput sgr0)  LESS_TERMCAP_ue=$(tput rmul; tput sgr0) \
-	LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) \
-	LESS_TERMCAP_se=$(tput rmso; tput sgr0)  \
-	LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) \
-	LESS_TERMCAP_mr=$(tput rev) LESS_TERMCAP_mh=$(tput dim)  \
-	LESS_TERMCAP_ZN=$(tput ssubm) LESS_TERMCAP_ZV=$(tput rsubm)  \
-	LESS_TERMCAP_ZO=$(tput ssupm) LESS_TERMCAP_ZW=$(tput rsupm)  \
 	GROFF_NO_SGR=1  # For Konsole and Gnome-terminal
 command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
 eval "$(pyenv init -)"
